development: &default
  adapter: postgresql
  database: pokemon_hot_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: pokemon_hot_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: 2

